In [2]:

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

from PIL import Image

In [4]:
df_discogs_electronic = pd.read_csv("data/discogs_electronic.csv")

In [5]:
df_discogs_electronic

,artist,title,label,country,format,release_date,genre,styles,have,want,num_ratings,average_rating,lowest_price,median_price,highest_price
0,Subterfuge,The Foundation Series Volume One,Visillusion,US,Vinyl,1997,Electronic,"House,Techno,Electro",93,423,31,3.81,$2.00,$39.02,$86.96
1,Titiyo,My Body Says Yes,Arista,UK,Vinyl,1991-04-01,Electronic,House,136,30,11,4.36,$0.43,$1.88,$5.43
2,Mariah Carey,Joy To The World,Columbia,US,Vinyl,1994-11,Electronic,"House,Garage House,Holiday",75,106,5,4.4,$1.99,$16.29,$33.71
3,Rhythmstate,Everybody,Nitebeat,US,Vinyl,1997,Electronic,"House,Breakbeat",22,57,6,4,$2.00,$7.00,$25.00
4,Exposé,"Stop, Listen, Look & Think",Arista,US,Vinyl,1990,Electronic,House,115,19,12,3.83,$0.79,$1.50,$4.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34918,Articolo 31,2030,Best Sound,Italy,Vinyl,1996,Hip Hop,Pop Rap,115,45,11,3.64,$3.80,$9.78,$19.57
34919,Cooly Live,That's What I Like (No Cream In My Coffee),RCA,US,Vinyl,1992,Hip Hop,NaN,47,9,5,3.8,$0.38,$1.97,$4.35
34920,The Deff Boyz,Swing,Fast Forward Records,UK,Vinyl,1990,Electronic,Hip-House,61,31,8,4.25,$0.33,$1.24,$4.35
34921,Navigators (2),Superstar,CNR Music Italia,Italy,Vinyl,1999,Electronic,"Pop Rap,Euro House",42,21,8,4,$0.87,$2.99,$5.43
34922,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,2000,Electronic,"Latin,Pop Rap",113,150,11,4.91,$3.80,$7.61,$18.48

In [6]:
unique_genres = df_discogs_electronic['genre'].unique()
unique_genres

array(['Electronic', 'Funk / Soul', 'Blues', 'Classical', 'Hip Hop'],
      dtype=object)

In [22]:
#genre = ['Electronic', 'Funk / Soul', 'Blues', 'Classical', 'Hip Hop']
#rel_genre = ['Funk / Soul']
#genre_mask = df_discogs_electronic['rel_genre'].isin(genre)

#df_country = df[country_mask]

df_discogs_mask = df_discogs_electronic[df_discogs_electronic['genre'] == 'Classical']
df_discogs_mask

,artist,title,label,country,format,release_date,genre,styles,have,want,num_ratings,average_rating,lowest_price,median_price,highest_price
30451,Gabrielle Roth & The Mirrors,Tongues,Aquarius International Music,US,CD,1995,Classical,"Downtempo,Ambient",3,10,0,--,$6.52,$6.52,$6.52

In [7]:
df_rated_entries = df_discogs_electronic[df_discogs_electronic['num_ratings'] == 0]
df_rated_entries

,artist,title,label,country,format,release_date,genre,styles,have,want,num_ratings,average_rating,lowest_price,median_price,highest_price
41,The Temptations,I'm Here (Metro Mix),Motown,US,Vinyl,2000,Electronic,"House,Acid Jazz",5,0,0,--,$2.34,$3.01,$3.69
137,The West Tribe,Hold Me Back !,K4B Records,US,Vinyl,1994-01-04,Electronic,House,4,9,0,--,$2.47,$2.47,$2.47
155,The Dope Wax All Stars,The Dope Wax All Stars,Dopewax,US,Vinyl,1990,Electronic,House,2,37,0,--,$5.00,$10.65,$16.30
218,Circuit Boy,Situation,KiKi Records,US,Vinyl,1998,Electronic,House,4,6,0,--,--,--,--
282,Delegation,The Mix,Metropol Records,Spain,Vinyl,1990,Electronic,House,28,18,0,--,$1.09,$4.61,$6.52
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34786,B.B. Jay,Hot Ta' Def / I Told You So,Jive,US,Vinyl,1999,Hip Hop,Conscious,57,6,0,--,$0.91,$1.24,$3.42
34803,Dr. Ease,Easetown Express,Bull'seye,UK & US,Vinyl,1990,Hip Hop,Electro,8,23,0,--,$2.50,$6.00,$12.00
34813,Sosay Redzs,G-Call / Throw It Up,Tourus Records,US,Vinyl,2000,Hip Hop,NaN,4,3,0,--,$1.12,$1.12,$1.12
34857,Black Daddy Magic,Leaving Me,Clinch Records (2),US,Vinyl,1992,Hip Hop,NaN,24,13,0,--,$0.99,$1.50,$5.42
34883,U.C.,Get Geeked!,Warlock Records,US,Vinyl,1993,Electronic,House,11,12,0,--,$1.50,$2.95,$4.00

In [9]:
df_discogs_electronic.dtypes

artist            object
title             object
label             object
country           object
format            object
release_date      object
genre             object
styles            object
have               int64
want               int64
num_ratings        int64
average_rating    object
lowest_price      object
median_price      object
highest_price     object
dtype: object

In [21]:
df_discogs.dtypes

release_id        int64
title            object
artist_id         int64
artist_name      object
label_name       object
label_id        float64
format           object
genre            object
style            object
country          object
release_date    float64
dtype: object

In [15]:
df_discogs_electronic['format'].value_counts()

format
Vinyl        31816
CD            3075
Laserdisc       21
Acetate          6
Box Set          3
All Media        1
CDV              1
Name: count, dtype: int64

In [4]:
df = pd.read_csv(filepath_or_buffer='data/discogs_electronic.csv')
df['lowest_price_(USD)'] = df['lowest_price'].apply(func=lambda x: np.nan if x == '--' else float(x.replace('$', '')))
df['median price_(USD)'] = df['median_price'].apply(func=lambda x: np.nan if x == '--' else float(x.replace('$', '')))
df['highest_price_(USD)'] = df['highest_price'].apply(func=lambda x: np.nan if x == '--' else float(x.replace('$', '')))
df['mean_rating'] = df['average_rating'].apply(func=lambda x: np.nan if x == '--' else float(x))
df['release_year'] = df['release_date'].apply(lambda x: int(x[:4]))

df.head()

,artist,title,label,country,format,release_date,genre,styles,have,want,num_ratings,average_rating,lowest_price,median_price,highest_price,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
0,Subterfuge,The Foundation Series Volume One,Visillusion,US,Vinyl,1997,Electronic,"House,Techno,Electro",93,423,31,3.81,$2.00,$39.02,$86.96,2.00,39.02,86.96,3.81,1997
1,Titiyo,My Body Says Yes,Arista,UK,Vinyl,1991-04-01,Electronic,House,136,30,11,4.36,$0.43,$1.88,$5.43,0.43,1.88,5.43,4.36,1991
2,Mariah Carey,Joy To The World,Columbia,US,Vinyl,1994-11,Electronic,"House,Garage House,Holiday",75,106,5,4.4,$1.99,$16.29,$33.71,1.99,16.29,33.71,4.40,1994
3,Rhythmstate,Everybody,Nitebeat,US,Vinyl,1997,Electronic,"House,Breakbeat",22,57,6,4,$2.00,$7.00,$25.00,2.00,7.00,25.00,4.00,1997
4,Exposé,"Stop, Listen, Look & Think",Arista,US,Vinyl,1990,Electronic,House,115,19,12,3.83,$0.79,$1.50,$4.34,0.79,1.50,4.34,3.83,1990

In [5]:
df_sorted = df.sort_values(by='release_year', ascending=True)
df_sorted

,artist,title,label,country,format,release_date,genre,styles,have,want,num_ratings,average_rating,lowest_price,median_price,highest_price,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
16,Julian Jonah,It's A Jungle Out There,Chrysalis,US,Vinyl,1990,Electronic,House,208,178,28,4.61,$1.09,$3.48,$7.61,1.09,3.48,7.61,4.61,1990
34907,Dj P. Project,Down On Me,World Deejay Foundation,NaN,Vinyl,1990,Electronic,Hip Hop,13,9,2,4.5,$2.17,$2.80,$3.26,2.17,2.80,3.26,4.50,1990
29080,Soul II Soul,Vol II - 1990 - A New Decade,Virgin,US,CD,1990,Electronic,"Downtempo,Neo Soul,RnB/Swing",65,35,8,4.75,$1.50,$2.81,$3.00,1.50,2.81,3.00,4.75,1990
29095,INXS,Bitter Tears,Atlantic,US,CD,1990,Electronic,"Progressive House,Synth-pop",221,54,27,3.85,$0.47,$6.12,$19.95,0.47,6.12,19.95,3.85,1990
2217,Cabaret Voltaire,Easy Life,Parlophone,UK,Vinyl,1990,Electronic,"Techno,House,Bleep",421,722,61,4.33,$12.35,$30.40,$59.78,12.35,30.40,59.78,4.33,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34904,Snoop Dogg,Ridaz With Me,TVT Records,US,Vinyl,2000,Hip Hop,Gangsta,108,25,7,4,$0.61,$1.62,$5.13,0.61,1.62,5.13,4.00,2000
34898,Sheeba Black,Check Yo' Style (Remix),Antra Records,US,Vinyl,2000,Hip Hop,NaN,37,5,2,3.5,$1.00,$1.00,$1.00,1.00,1.00,1.00,3.50,2000
41,The Temptations,I'm Here (Metro Mix),Motown,US,Vinyl,2000,Electronic,"House,Acid Jazz",5,0,0,--,$2.34,$3.01,$3.69,2.34,3.01,3.69,NaN,2000
34922,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,2000,Electronic,"Latin,Pop Rap",113,150,11,4.91,$3.80,$7.61,$18.48,3.80,7.61,18.48,4.91,2000
8,98°,Give Me Just One Night (Una Noche) (Remixes),Universal Records,US,Vinyl,2000,Electronic,House,59,20,1,5,$0.50,$1.99,$10.01,0.50,1.99,10.01,5.00,2000

In [7]:
df_sorted = df_sorted.drop(columns=['release_date', 'lowest_price', 'median_price', 'highest_price'])

In [9]:
df_sorted = df_sorted.drop(columns=['average_rating'])

In [10]:
df_sorted

,artist,title,label,country,format,genre,styles,have,want,num_ratings,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
16,Julian Jonah,It's A Jungle Out There,Chrysalis,US,Vinyl,Electronic,House,208,178,28,1.09,3.48,7.61,4.61,1990
34907,Dj P. Project,Down On Me,World Deejay Foundation,NaN,Vinyl,Electronic,Hip Hop,13,9,2,2.17,2.80,3.26,4.50,1990
29080,Soul II Soul,Vol II - 1990 - A New Decade,Virgin,US,CD,Electronic,"Downtempo,Neo Soul,RnB/Swing",65,35,8,1.50,2.81,3.00,4.75,1990
29095,INXS,Bitter Tears,Atlantic,US,CD,Electronic,"Progressive House,Synth-pop",221,54,27,0.47,6.12,19.95,3.85,1990
2217,Cabaret Voltaire,Easy Life,Parlophone,UK,Vinyl,Electronic,"Techno,House,Bleep",421,722,61,12.35,30.40,59.78,4.33,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34904,Snoop Dogg,Ridaz With Me,TVT Records,US,Vinyl,Hip Hop,Gangsta,108,25,7,0.61,1.62,5.13,4.00,2000
34898,Sheeba Black,Check Yo' Style (Remix),Antra Records,US,Vinyl,Hip Hop,NaN,37,5,2,1.00,1.00,1.00,3.50,2000
41,The Temptations,I'm Here (Metro Mix),Motown,US,Vinyl,Electronic,"House,Acid Jazz",5,0,0,2.34,3.01,3.69,NaN,2000
34922,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,Electronic,"Latin,Pop Rap",113,150,11,3.80,7.61,18.48,4.91,2000
8,98°,Give Me Just One Night (Una Noche) (Remixes),Universal Records,US,Vinyl,Electronic,House,59,20,1,0.50,1.99,10.01,5.00,2000

In [11]:
df_sorted.to_csv('data/discogs_electronic_90s.csv', index=False)

In [25]:
df_90s = pd.read_csv("data/discogs_electronic_90s.csv")

In [26]:
df_90s

,artist,title,label,country,format,genre,styles,have,want,num_ratings,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
0,Julian Jonah,It's A Jungle Out There,Chrysalis,US,Vinyl,Electronic,House,208,178,28,1.09,3.48,7.61,4.61,1990
1,Dj P. Project,Down On Me,World Deejay Foundation,NaN,Vinyl,Electronic,Hip Hop,13,9,2,2.17,2.80,3.26,4.50,1990
2,Soul II Soul,Vol II - 1990 - A New Decade,Virgin,US,CD,Electronic,"Downtempo,Neo Soul,RnB/Swing",65,35,8,1.50,2.81,3.00,4.75,1990
3,INXS,Bitter Tears,Atlantic,US,CD,Electronic,"Progressive House,Synth-pop",221,54,27,0.47,6.12,19.95,3.85,1990
4,Cabaret Voltaire,Easy Life,Parlophone,UK,Vinyl,Electronic,"Techno,House,Bleep",421,722,61,12.35,30.40,59.78,4.33,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34918,Snoop Dogg,Ridaz With Me,TVT Records,US,Vinyl,Hip Hop,Gangsta,108,25,7,0.61,1.62,5.13,4.00,2000
34919,Sheeba Black,Check Yo' Style (Remix),Antra Records,US,Vinyl,Hip Hop,NaN,37,5,2,1.00,1.00,1.00,3.50,2000
34920,The Temptations,I'm Here (Metro Mix),Motown,US,Vinyl,Electronic,"House,Acid Jazz",5,0,0,2.34,3.01,3.69,NaN,2000
34921,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,Electronic,"Latin,Pop Rap",113,150,11,3.80,7.61,18.48,4.91,2000
34922,98°,Give Me Just One Night (Una Noche) (Remixes),Universal Records,US,Vinyl,Electronic,House,59,20,1,0.50,1.99,10.01,5.00,2000

In [27]:
df_90s.dtypes

artist                  object
title                   object
label                   object
country                 object
format                  object
genre                   object
styles                  object
have                     int64
want                     int64
num_ratings              int64
lowest_price_(USD)     float64
median price_(USD)     float64
highest_price_(USD)    float64
mean_rating            float64
release_year             int64
dtype: object

In [38]:
virgin = df_90s.loc[df_90s['artist'] == 'Dj P. Project']
virgin

,artist,title,label,country,format,genre,styles,have,want,num_ratings,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
1,Dj P. Project,Down On Me,World Deejay Foundation,NaN,Vinyl,Electronic,Hip Hop,13,9,2,2.17,2.8,3.26,4.5,1990

In [4]:
df_discogs = pd.read_csv("data/discogs.csv")

In [13]:
df_discogs = df_discogs.drop(columns=['notes', 'video_url', 'company_name', 'status', 'id',])
df_discogs

,release_id,title,artist_id,artist_name,label_name,label_id,format,genre,style,country,release_date,master_id
0,12295801,The World Of Ray Price,311678,Ray Price,Columbia,1866.0,8-Track Cartridge,"Folk, World, & Country",NaN,US,1970.0,NaN
1,12295802,The Burden of Isolation,3720243,Filth (9),Not on Label (Filth (9) Self-Released),1495843.0,CD,Rock,Deathcore,US,2018.0,1397110.0
2,12295803,Bassoon Concertos,6095671,Sebastian Fagerlund,BIS,51038.0,SACD,Classical,Contemporary,Sweden,2016.0,NaN
3,12295805,Ich Lag In Einer Nacht Und Schlief,3170804,Hans Peter Treichler,Gold Records,11489.0,Vinyl,Pop,NaN,Switzerland,1980.0,NaN
4,12295806,Bien O Mal,85181,Julieta Venegas,Sony Music,25487.0,CD,Latin,NaN,Argentina,2010.0,1418114.0
...,...,...,...,...,...,...,...,...,...,...,...,...
16319269,12271885,Bass Culture,20702,Linton Kwesi Johnson,Mango,10923.0,CD,Reggae,Dub Poetry,UK & Europe,NaN,NaN
16319270,12247803,22 Legendary Hits,330342,The Four Freshmen,CEMA Special Markets,14703.0,CD,Pop,Vocal,US,1995.0,NaN
16319271,12259913,Ciclo Basico,6589308,Jano Zanzi,Oasis Records Uruguay,1491790.0,CD,Rock,NaN,Uruguay,2003.0,1393093.0
16319272,12271886,We'll Fall Together,6594554,Austin Jones (2),Not On Label (Austin Jones (2) Self-released),1493139.0,File,Rock,Pop Rock,NaN,2013.0,NaN
16319273,12271887,Touch Me In The Morning,47742,Diana Ross,Motown,1723.0,Vinyl,Funk / Soul,Soul,US,1973.0,NaN

In [14]:
df_discogs = df_discogs.drop(columns=['master_id'])

In [22]:
df_discogs_clean = df_discogs.dropna()
df_discogs_clean

,release_id,title,artist_id,artist_name,label_name,label_id,format,genre,style,country,release_date
1,12295802,The Burden of Isolation,3720243,Filth (9),Not on Label (Filth (9) Self-Released),1495843.0,CD,Rock,Deathcore,US,2018.0
2,12295803,Bassoon Concertos,6095671,Sebastian Fagerlund,BIS,51038.0,SACD,Classical,Contemporary,Sweden,2016.0
5,12295807,Kaleidoscopia,3130927,Beatnik (8),Eargasm Wreckords,500315.0,CD,Rock,Krautrock,Switzerland,2008.0
7,12295809,Frescobaldi Edition Vol 6 - Il Primo Libro Dei...,834330,Girolamo Frescobaldi,Brilliant Classics,89052.0,CD,Classical,Renaissance,Netherlands,2009.0
9,12295811,A Tribute to La Monte Young,6522519,Infinite Music,Fire Records,2051.0,CD,Electronic,Minimal,UK,2018.0
...,...,...,...,...,...,...,...,...,...,...,...
16319264,12247800,Gypsy Woman,60917,Leroy Gomez,Casablanca,26938.0,Vinyl,Electronic,Disco,Mexico,1978.0
16319265,12259910,Kick,54650,INXS,Petrol Electric,247980.0,CD,Rock,Pop Rock,Australia,2012.0
16319266,12271883,Parsec,807907,Tobor Experiment,Not On Label (Tobor Experiment Self-released),221450.0,File,Electronic,House,Italy,2017.0
16319270,12247803,22 Legendary Hits,330342,The Four Freshmen,CEMA Special Markets,14703.0,CD,Pop,Vocal,US,1995.0
16319273,12271887,Touch Me In The Morning,47742,Diana Ross,Motown,1723.0,Vinyl,Funk / Soul,Soul,US,1973.0

In [29]:
df_discogs_clean.dtypes

release_id        int64
title            object
artist_id         int64
artist_name      object
label_name       object
label_id        float64
format           object
genre            object
style            object
country          object
release_date    float64
release_year      int64
dtype: object

In [28]:
df_discogs_clean['release_year'] = df_discogs_clean['release_date'].astype('int64')

C:\Users\flpzi\AppData\Local\Temp\ipykernel_7424\4019387178.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_discogs_clean['release_year'] = df_discogs_clean['release_date'].astype('int64')

In [31]:
df_discogs_clean = df_discogs_clean.drop(columns=['release_date'])

In [39]:
df_discogs_clean = df_discogs_clean.sort_values(by='release_year', ascending=True)

In [51]:
num_rows_with_zero = df_discogs_clean['release_year'].value_counts().get(1940, 1940)
print(f"Number of rows with 0 in 'release_year': {num_rows_with_zero}")

Number of rows with 0 in 'release_year': 3997

Now i want to see which is the first electronic release, and then i am going to delete all the rows that have release year before that.

In [53]:
df_clean_electronic = df_discogs_clean[df_discogs_clean['genre'] == 'Electronic']

In [57]:
df_clean_electronic.head(15)

,release_id,title,artist_id,artist_name,label_name,label_id,format,genre,style,country,release_year
5468956,22423120,Vorbei Ist Die Zeit,185546,Parsifal,Help Records (3),161503.0,Vinyl,Electronic,Synth-pop,Austria,0
6352493,25162438,Got It All,436586,Erik de Vahl,Service,38025.0,CDr,Electronic,Indie Pop,Sweden,0
6954399,26940884,Hop Step Techno-Pop,4041654,Digitals,Hotatekno,989473.0,CDr,Electronic,J-pop,Japan,0
6979485,27021054,Underground,6000168,Jucci Da Funk,Wuiesh Recordings,3252111.0,Vinyl,Electronic,Deep House,UK,0
4708331,19541008,Fire in the Heart,9686926,Jaya Gaia,Not On Label,1818.0,Cassette,Electronic,New Age,US,0
6990519,1971239,Medley Gloria + Sukuleu,1602321,Gloria In House,Not On Label,1818.0,Vinyl,Electronic,House,Italy,0
6794859,26455781,Complete Dramatized Tour,50263,Yes,Highland,85848.0,CD,Electronic,Prog Rock,Japan,0
6853605,26654429,Whigfield,14643,Whigfield,VMP,105620.0,Cassette,Electronic,Electro,Thailand,0
4568993,19330378,Corale / Serenata,204156,Antonio Russolo,"Società Anonima Nazionale Del ""Grammofono""",536112.0,Shellac,Electronic,Electroacoustic,Italy,1924
2978414,15567549,Ondes Martenot,355,Unknown Artist,Not On Label,1818.0,Shellac,Electronic,Experimental,France,1937
14064024,9675680,Novachord Solos,2058726,Fred Feibel,Columbia,1866.0,Shellac,Electronic,Instrumental,US,1941
2191378,14680277,Music Out Of The Moon: Music Unusual Featuring...,643490,Harry Revel,Capitol Records,654.0,Vinyl,Electronic,Space-Age,US,1950
9270430,4168420,Music Out Of The Moon (Music Unusual Featuring...,643490,Harry Revel,Capitol Records,654.0,Vinyl,Electronic,Space-Age,US,1950
5575199,22581794,Étude Pathétique / Bidule En Ut,32181,Pierre Schaeffer,Not On Label,1818.0,Acetate,Electronic,Musique Concrète,France,1950
9481136,4488668,Music Out Of The Moon: Music Unusual Featuring...,643490,Harry Revel,Capitol Records,654.0,Vinyl,Electronic,Space-Age,US,1950

In [56]:
num_rows_with_zero = df_clean_electronic['release_year'].value_counts().get(0, 0)
print(f"Number of rows with 0 in 'release_year': {num_rows_with_zero}")

Number of rows with 0 in 'release_year': 8

now i am going to get rid of all the rows with the release_year less than 1950, seeing that there is only a couple of releases before that year, and the first releases on vinyl are from the year 1950, and also, around that year were the first musique concrete releases, which is generally considered the beginning of modern electronical music

In [60]:
mask = df_discogs_clean['release_year'] >= 1950

df_discogs_clean = df_discogs_clean[mask]

In [61]:
df_discogs_clean

,release_id,title,artist_id,artist_name,label_name,label_id,format,genre,style,country,release_year
14403630,10062059,I Won't Be Home / Dear Little Girls,439533,Red Foley,Decca,5320.0,Shellac,Pop,Country,US,1950
10897116,6072172,Polka!,899033,Tex Williams And His Western Caravan,Capitol Records,654.0,Vinyl,"Folk, World, & Country",Country,US,1950
6381566,25174888,"The Wedding Samba / I See, I See = Asi Asi",299951,The Andrews Sisters,Decca,5320.0,Shellac,Latin,Vocal,US,1950
15150918,10916559,The Baseball Polka / Polka Recipe,1308713,Johnny Vadnal And His Orchestra,RCA Victor,11358.0,Shellac,Pop,Polka,US,1950
16023631,11946636,Senorita / If I Steal A Kiss,52833,Frank Sinatra,Columbia,1866.0,Shellac,Jazz,Vocal,Australia,1950
...,...,...,...,...,...,...,...,...,...,...,...
6808556,26669495,Interludium,816855,Powerwolf,Napalm Records,33182.0,CD,Rock,Power Metal,Europe,2023
6808541,26704481,Way Out,10793125,Qeddeshet,Not On Label (Qeddeshet Self-released),2629684.0,File,Rock,Death Metal,Japan,2023
6808539,26565155,"If You Were A Movie, This Would Be Your Soundt...",2217424,Sleeping With Sirens,Rise Records (3),165412.0,Vinyl,Rock,Alternative Rock,US,2023
6654951,26051551,Violent Theatre,5140571,Mephistofeles,Regain Records,21049.0,Vinyl,Rock,Stoner Rock,Sweden,2023
6654454,26051335,Hatching Under The Stars,1418599,Clara Engel,oscarson,541804.0,Vinyl,"Folk, World, & Country",Folk,Germany,2023

In [65]:
df_discogs_clean.to_csv('data/discogs_clean.csv', index=False)

In [66]:
df_discogs = pd.read_csv("data/discogs_clean.csv")

In [68]:
df_discogs

,release_id,title,artist_id,artist_name,label_name,label_id,format,genre,style,country,release_year
0,10062059,I Won't Be Home / Dear Little Girls,439533,Red Foley,Decca,5320.0,Shellac,Pop,Country,US,1950
1,6072172,Polka!,899033,Tex Williams And His Western Caravan,Capitol Records,654.0,Vinyl,"Folk, World, & Country",Country,US,1950
2,25174888,"The Wedding Samba / I See, I See = Asi Asi",299951,The Andrews Sisters,Decca,5320.0,Shellac,Latin,Vocal,US,1950
3,10916559,The Baseball Polka / Polka Recipe,1308713,Johnny Vadnal And His Orchestra,RCA Victor,11358.0,Shellac,Pop,Polka,US,1950
4,11946636,Senorita / If I Steal A Kiss,52833,Frank Sinatra,Columbia,1866.0,Shellac,Jazz,Vocal,Australia,1950
...,...,...,...,...,...,...,...,...,...,...,...
11641474,26669495,Interludium,816855,Powerwolf,Napalm Records,33182.0,CD,Rock,Power Metal,Europe,2023
11641475,26704481,Way Out,10793125,Qeddeshet,Not On Label (Qeddeshet Self-released),2629684.0,File,Rock,Death Metal,Japan,2023
11641476,26565155,"If You Were A Movie, This Would Be Your Soundt...",2217424,Sleeping With Sirens,Rise Records (3),165412.0,Vinyl,Rock,Alternative Rock,US,2023
11641477,26051551,Violent Theatre,5140571,Mephistofeles,Regain Records,21049.0,Vinyl,Rock,Stoner Rock,Sweden,2023
11641478,26051335,Hatching Under The Stars,1418599,Clara Engel,oscarson,541804.0,Vinyl,"Folk, World, & Country",Folk,Germany,2023

In [69]:
df_discogs.rename(columns={
    'artist_name': 'artist',
    'label_name': 'label',
    'style': 'styles'
}, inplace=True)

In [70]:
new_order = [
    'artist', 'title', 'label', 'country', 'format',
    'genre', 'styles', 'release_id', 'artist_id',
    'label_id', 'release_year'
]

df_discogs = df_discogs[new_order]
df_discogs

,artist,title,label,country,format,genre,styles,release_id,artist_id,label_id,release_year
0,Red Foley,I Won't Be Home / Dear Little Girls,Decca,US,Shellac,Pop,Country,10062059,439533,5320.0,1950
1,Tex Williams And His Western Caravan,Polka!,Capitol Records,US,Vinyl,"Folk, World, & Country",Country,6072172,899033,654.0,1950
2,The Andrews Sisters,"The Wedding Samba / I See, I See = Asi Asi",Decca,US,Shellac,Latin,Vocal,25174888,299951,5320.0,1950
3,Johnny Vadnal And His Orchestra,The Baseball Polka / Polka Recipe,RCA Victor,US,Shellac,Pop,Polka,10916559,1308713,11358.0,1950
4,Frank Sinatra,Senorita / If I Steal A Kiss,Columbia,Australia,Shellac,Jazz,Vocal,11946636,52833,1866.0,1950
...,...,...,...,...,...,...,...,...,...,...,...
11641474,Powerwolf,Interludium,Napalm Records,Europe,CD,Rock,Power Metal,26669495,816855,33182.0,2023
11641475,Qeddeshet,Way Out,Not On Label (Qeddeshet Self-released),Japan,File,Rock,Death Metal,26704481,10793125,2629684.0,2023
11641476,Sleeping With Sirens,"If You Were A Movie, This Would Be Your Soundt...",Rise Records (3),US,Vinyl,Rock,Alternative Rock,26565155,2217424,165412.0,2023
11641477,Mephistofeles,Violent Theatre,Regain Records,Sweden,Vinyl,Rock,Stoner Rock,26051551,5140571,21049.0,2023
11641478,Clara Engel,Hatching Under The Stars,oscarson,Germany,Vinyl,"Folk, World, & Country",Folk,26051335,1418599,541804.0,2023

In [71]:
df_90s

,artist,title,label,country,format,genre,styles,have,want,num_ratings,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
0,Julian Jonah,It's A Jungle Out There,Chrysalis,US,Vinyl,Electronic,House,208,178,28,1.09,3.48,7.61,4.61,1990
1,Dj P. Project,Down On Me,World Deejay Foundation,NaN,Vinyl,Electronic,Hip Hop,13,9,2,2.17,2.80,3.26,4.50,1990
2,Soul II Soul,Vol II - 1990 - A New Decade,Virgin,US,CD,Electronic,"Downtempo,Neo Soul,RnB/Swing",65,35,8,1.50,2.81,3.00,4.75,1990
3,INXS,Bitter Tears,Atlantic,US,CD,Electronic,"Progressive House,Synth-pop",221,54,27,0.47,6.12,19.95,3.85,1990
4,Cabaret Voltaire,Easy Life,Parlophone,UK,Vinyl,Electronic,"Techno,House,Bleep",421,722,61,12.35,30.40,59.78,4.33,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34918,Snoop Dogg,Ridaz With Me,TVT Records,US,Vinyl,Hip Hop,Gangsta,108,25,7,0.61,1.62,5.13,4.00,2000
34919,Sheeba Black,Check Yo' Style (Remix),Antra Records,US,Vinyl,Hip Hop,NaN,37,5,2,1.00,1.00,1.00,3.50,2000
34920,The Temptations,I'm Here (Metro Mix),Motown,US,Vinyl,Electronic,"House,Acid Jazz",5,0,0,2.34,3.01,3.69,NaN,2000
34921,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,Electronic,"Latin,Pop Rap",113,150,11,3.80,7.61,18.48,4.91,2000
34922,98°,Give Me Just One Night (Una Noche) (Remixes),Universal Records,US,Vinyl,Electronic,House,59,20,1,0.50,1.99,10.01,5.00,2000

In [72]:
df_90s_clean = df_90s.dropna()
df_90s_clean

,artist,title,label,country,format,genre,styles,have,want,num_ratings,lowest_price_(USD),median price_(USD),highest_price_(USD),mean_rating,release_year
0,Julian Jonah,It's A Jungle Out There,Chrysalis,US,Vinyl,Electronic,House,208,178,28,1.09,3.48,7.61,4.61,1990
2,Soul II Soul,Vol II - 1990 - A New Decade,Virgin,US,CD,Electronic,"Downtempo,Neo Soul,RnB/Swing",65,35,8,1.50,2.81,3.00,4.75,1990
3,INXS,Bitter Tears,Atlantic,US,CD,Electronic,"Progressive House,Synth-pop",221,54,27,0.47,6.12,19.95,3.85,1990
4,Cabaret Voltaire,Easy Life,Parlophone,UK,Vinyl,Electronic,"Techno,House,Bleep",421,722,61,12.35,30.40,59.78,4.33,1990
5,Musto & Bones,Dangerous On The Dancefloor,City Beat,UK,Vinyl,Electronic,"Downtempo,Hip-House,House",159,69,24,1.09,3.36,9.86,4.50,1990
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34916,Madison Avenue,Who The Hell Are You,Dance Pool,Italy,Vinyl,Electronic,House,170,60,17,0.50,3.20,13.04,3.88,2000
34917,Sylvester Burns,Been There,Teardrop Records,UK,Vinyl,Electronic,House,42,7,5,0.25,1.00,6.99,3.60,2000
34918,Snoop Dogg,Ridaz With Me,TVT Records,US,Vinyl,Hip Hop,Gangsta,108,25,7,0.61,1.62,5.13,4.00,2000
34921,Orishas,A Lo Cubano,Dance Factory (2),Italy,Vinyl,Electronic,"Latin,Pop Rap",113,150,11,3.80,7.61,18.48,4.91,2000
34922,98°,Give Me Just One Night (Una Noche) (Remixes),Universal Records,US,Vinyl,Electronic,House,59,20,1,0.50,1.99,10.01,5.00,2000

In [74]:
df_90s_clean.to_csv('data/discogs_electr_90s_clean.csv', index=False)

In [73]:
df_discogs.to_csv('data/discogs_clean.csv', index=False)

In [3]:
df_music_sales = pd.read_csv("data/MusicData.csv")
df_music_sales

,index,Format,Metric,Year,Number of Records,Value (Actual)
0,0,CD,Units,1973,1,NaN
1,1,CD,Units,1974,1,NaN
2,2,CD,Units,1975,1,NaN
3,3,CD,Units,1976,1,NaN
4,4,CD,Units,1977,1,NaN
...,...,...,...,...,...,...
3003,3003,Vinyl Single,Value (Adjusted),2015,1,6.205390
3004,3004,Vinyl Single,Value (Adjusted),2016,1,5.198931
3005,3005,Vinyl Single,Value (Adjusted),2017,1,6.339678
3006,3006,Vinyl Single,Value (Adjusted),2018,1,5.386197
3007,3007,Vinyl Single,Value (Adjusted),2019,1,6.795946

In [4]:
df_music_sales['Metric'].unique()

array(['Units', 'Value', 'Value (Adjusted)'], dtype=object)

In [5]:
df_music_sales = df_music_sales.sort_values(by='Year', ascending=True)

In [6]:
df_music_sales

,index,Format,Metric,Year,Number of Records,Value (Actual)
1598,1598,Other Tapes,Value,1973,1,15.600000
1645,1645,Paid Subscription,Value,1973,1,NaN
1692,1692,Ringtones & Ringbacks,Value,1973,1,NaN
2726,2726,Paid Subscription,Value (Adjusted),1973,1,NaN
1457,1457,On-Demand Streaming (Ad-Supported),Value,1973,1,NaN
...,...,...,...,...,...,...
328,328,8 - Track,Units,2019,1,NaN
140,140,Cassette,Units,2019,1,NaN
187,187,Cassette Single,Units,2019,1,NaN
93,93,CD Single,Units,2019,1,0.026257
46,46,CD,Units,2019,1,46.506496

In [10]:
df_music_sales_clean = df_music_sales.dropna()
df_music_sales_clean

,index,Format,Metric,Year,Number of Records,Value (Actual)
1598,1598,Other Tapes,Value,1973,1,15.600000
1316,1316,LP/EP,Value,1973,1,1246.000000
94,94,Cassette,Units,1973,1,15.000000
1000,1000,8 - Track,Value,1973,1,489.000000
2679,2679,Other Tapes,Value (Adjusted),1973,1,89.825432
940,940,Cassette,Value,1973,1,76.000000
2068,2068,Cassette,Value (Adjusted),1973,1,437.611081
1927,1927,8 - Track,Value (Adjusted),1973,1,2815.681824
1880,1880,Vinyl Single,Value,1973,1,190.000000
2961,2961,Vinyl Single,Value (Adjusted),1973,1,1094.027703
2397,2397,LP/EP,Value (Adjusted),1973,1,7174.518514
329,329,Other Tapes,Units,1973,1,2.200000
188,188,LP/EP,Units,1973,1,280.000000
235,235,Vinyl Single,Units,1973,1,228.000000
282,282,8 - Track,Units,1973,1,91.000000
941,941,Cassette,Value,1974,1,87.200000
2069,2069,Cassette,Value (Adjusted),1974,1,452.196560
95,95,Cassette,Units,1974,1,15.300000
1001,1001,8 - Track,Value,1974,1,549.200000
1928,1928,8 - Track,Value (Adjusted),1974,1,2848.008609

In [14]:
df_music_sales_clean = df_music_sales_clean.drop(columns=['index', 'Number of Records'])
df_music_sales_clean

               Format            Metric  Year  Value (Actual)
1598      Other Tapes             Value  1973       15.600000
1316            LP/EP             Value  1973     1246.000000
94           Cassette             Units  1973       15.000000
1000        8 - Track             Value  1973      489.000000
2679      Other Tapes  Value (Adjusted)  1973       89.825432
...               ...               ...   ...             ...
563   Download Single             Units  2019      335.339194
234             LP/EP             Units  2019       19.103163
281      Vinyl Single             Units  2019        0.336120
93          CD Single             Units  2019        0.026257
46                 CD             Units  2019       46.506496

[1351 rows x 4 columns]

In [15]:
df_music_sales_clean.to_csv('data/music_sales_clean.csv', index=False)

In [17]:
df_music_sales_clean = pd.read_csv("data/music_sales_clean.csv")

In [18]:
df_music_sales_clean

               Format            Metric  Year  Value (Actual)
0         Other Tapes             Value  1973       15.600000
1               LP/EP             Value  1973     1246.000000
2            Cassette             Units  1973       15.000000
3           8 - Track             Value  1973      489.000000
4         Other Tapes  Value (Adjusted)  1973       89.825432
...               ...               ...   ...             ...
1346  Download Single             Units  2019      335.339194
1347            LP/EP             Units  2019       19.103163
1348     Vinyl Single             Units  2019        0.336120
1349        CD Single             Units  2019        0.026257
1350               CD             Units  2019       46.506496

[1351 rows x 4 columns]